# Generated by Django 5.0.4 on 2024-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalworkout',
            name='visibility',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalworkout',
            name='visibility',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
