# Generated by Django 5.0.4 on 2024-05-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
    ]
