# Generated by Django 5.0.4 on 2024-05-21 18:20

import trener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0002_generalworkout_visibility_personalworkout_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=trener.models.exercise_directory_path)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('active_until', 'Active until specific date')], default='active', max_length=15)),
                ('active_until', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
