# Generated by Django 5.0.4 on 2024-05-22 20:26

import django.db.models.deletion
import trener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0003_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalworkout',
            name='client',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='trener.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=trener.models.client_directory_path),
        ),
    ]
