# Generated by Django 5.0 on 2024-09-04 22:52

from django.db import migrations

def create_initial_data(apps, schema_editor):
    WaterNeed = apps.get_model('trener', 'WaterNeed')
    LightRequirement = apps.get_model('trener', 'LightRequirement')
    CareLevel = apps.get_model('trener', 'CareLevel')

    # Dodaj predefiniowane wartości dla WaterNeed
    WaterNeed.objects.create(name='Niewielka - rzadziej niż raz w miesiącu')
    WaterNeed.objects.create(name='Umiarkowana - raz na 2-3 tygodnie')
    WaterNeed.objects.create(name='Wysoka - raz w tygodniu lub częściej')

    # Dodaj predefiniowane wartości dla LightRequirement
    LightRequirement.objects.create(name='Zacienione - brak bezpośredniego światła słonecznego')
    LightRequirement.objects.create(name='Częściowe zacienienie - jasne światło, ale bez bezpośredniego słońca')
    LightRequirement.objects.create(name='Pośrednie światło - jasne, ale rozproszone światło')
    LightRequirement.objects.create(name='Jasne światło - kilka godzin bezpośredniego światła słonecznego')
    LightRequirement.objects.create(name='Pełne słońce - bezpośrednie światło słoneczne przez większość dnia')

    # Dodaj predefiniowane wartości dla CareLevel
    CareLevel.objects.create(name='Niski - minimalna pielęgnacja, idealne dla początkujących')
    CareLevel.objects.create(name='Średni - regularna pielęgnacja, dobra dla osób z pewnym doświadczeniem')
    CareLevel.objects.create(name='Wysoki - intensywna pielęgnacja, wymaga poświęcenia i wiedzy')

class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0003_auto_20240905_0051'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
