# Generated by Django 5.0 on 2024-09-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0005_alter_carelevel_name'),
    ]

    operations = [
    ]
