# Generated by Django 5.0 on 2024-09-04 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trener', '0008_auto_20240905_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='water_need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trener.waterneed', verbose_name='Potrzeba wody'),
        ),
    ]
